# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{i18n_yaml_sorter}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bernardo de P\303\241dua"]
  s.date = %q{2010-03-11}
  s.default_executable = %q{sort_yaml}
  s.description = %q{ Allows you to deep sort YAML files that are mainly composed of 
      nested hashes and string values. Great to sort your rails I18n YAML files. You can easily
      add it to a textmate bundle, rake task, or just use the included regular comand line tool. 
    }
  s.email = %q{berpasan@gmail.com}
  s.executables = ["sort_yaml"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/sort_yaml",
     "i18n_yaml_sorter.gemspec",
     "lib/i18n_yaml_sorter.rb",
     "test/helper.rb",
     "test/in.yml",
     "test/out.yml",
     "test/test_i18n_yaml_sorter.rb"
  ]
  s.homepage = %q{http://github.com/redealumni/i18n_yaml_sorter}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A I18n YAML deep sorter that will keep your locales organized and not screw up your text formating}
  s.test_files = [
    "test/helper.rb",
     "test/test_i18n_yaml_sorter.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

