# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "i18n_yaml_sorter"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bernardo de P\u{e1}dua"]
  s.date = "2011-11-29"
  s.description = " Allows you to deep sort YAML files that are mainly composed of \n      nested hashes and string values. Great to sort your rails I18n YAML files. You can easily\n      add it to a textmate bundle, rake task, or just use the included regular comand line tool. \n    "
  s.email = "berpasan@gmail.com"
  s.executables = ["sort_yaml"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/sort_yaml",
    "i18n_yaml_sorter.gemspec",
    "lib/i18n_yaml_sorter.rb",
    "lib/i18n_yaml_sorter/railtie.rb",
    "lib/i18n_yaml_sorter/sorter.rb",
    "lib/tasks/i18n_yaml_sorter.rake",
    "test/helper.rb",
    "test/in.yml",
    "test/in_rails.yml",
    "test/in_simple.yml",
    "test/out.yml",
    "test/out_rails.yml",
    "test/out_simple.yml",
    "test/test_i18n_yaml_sorter.rb",
    "textmate/YAML Sort.tmbundle/Commands/Sort YAML.tmCommand",
    "textmate/YAML Sort.tmbundle/info.plist"
  ]
  s.homepage = "http://github.com/redealumni/i18n_yaml_sorter"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "A I18n YAML deep sorter that will keep your locales organized and not screw up your text formating"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

